module.exports = {
    preset: 'jest-expo',
    setupFilesAfterEnv: ['./tests/config/jest/jest.setup.ts'],
    collectCoverageFrom: [
        '**/*.{ts,tsx}',
        '!**/node_modules/**',
        '!**/app/**/_layout.tsx',
        '!**/components/types/**',
        '!**/providers/root-provider/**',
        '!**/providers/types/**',
        '!**/tests/**',
        '!**/@types/**',
        '!**/services/apis/**',
    ],
    moduleNameMapper: {
        '^@components$': '<rootDir>/src/components',
        '^@functions$': '<rootDir>/src/functions',
        '^@constants$': '<rootDir>/src/constants',
        '^@hooks$': '<rootDir>/src/hooks',
        '^@store$': '<rootDir>/src/store',
        '^@services$': '<rootDir>/src/services',
        '^@utils$': '<rootDir>/src/utils',
        '^@enums$': '<rootDir>/src/enums',
        '^@providers$': '<rootDir>/src/providers',
        '^@tests/(.*)$': '<rootDir>/tests/$1',
    },
}
